export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const SET_CART = 'SET_CART';


export const CREATE_CART_ITEMS_ORDER_REQUEST = 'CREATE_CART_ITEMS_ORDER_REQUEST';
export const CREATE_CART_ITEMS_ORDER_SUCCESS = 'CREATE_CART_ITEMS_ORDER_SUCCESS';
export const CREATE_CART_ITEMS_ORDER_FAILURE = 'CREATE_CART_ITEMS_ORDER_FAILURE';