export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const FETCH_ORDER_HISTORY_REQUEST = 'FETCH_ORDER_HISTORY_REQUEST';
export const FETCH_ORDER_HISTORY_REQUEST_SUCCESS = 'FETCH_ORDER_HISTORY_REQUEST_SUCCESS';
export const FETCH_ORDER_HISTORY_REQUEST_FAILURE = 'FETCH_ORDER_HISTORY_REQUEST_FAILURE';