export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

export const FETCH_BESTSELLING_PRODUCTS_REQUEST = 'FETCH_BESTSELLING_PRODUCTS_REQUEST';
export const FETCH_BESTSELLING_PRODUCTS_SUCCESS = 'FETCH_BESTSELLING_PRODUCTS_SUCCESS';
export const FETCH_BESTSELLING_PRODUCTS_FAILURE = 'FETCH_BESTSELLING_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_FAVORITE_PRODUCT_REQUEST='FETCH_FAVORITE_PRODUCT_REQUEST'
export const FETCH_FAVORITE_PRODUCT_SUCCESS='FETCH_FAVORITE_PRODUCT_SUCCESS'
export const FETCH_FAVORITE_PRODUCT_FAILURE='FETCH_FAVORITE_PRODUCT_FAILURE'

export const SET_FAVORITE_PRODUCT_REQUEST='SET_FAVORITE_PRODUCT_REQUEST'
export const SET_FAVORITE_PRODUCT_SUCCESS ='SET_FAVORITE_PRODUCT_SUCCESS'
export const SET_FAVORITE_PRODUCT_FAILURE ='SET_FAVORITE_PRODUCT_FAILURE'
